## <strong>2. NumPy: Universal Functions (UFunc)</strong>

In [36]:
import numpy as np

In [34]:
# 역수 계산 함수
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# [+] 함수 테스트
values = np.random.randint(1,10, size=5)

In [30]:
compute_reciprocals(values)

array([0.2       , 0.125     , 0.5       , 0.125     , 0.33333333])

#### <strong>역수 계산: Python loop vs NumPy ufuncs</strong>
+ ```%timeit```: 셀 단위 코드 실행 시간을 측정하는 매직 함수

In [35]:
# [+] 백만 개 크기의 난수 배열 생성: 정수, 값 범위 [1, 100)
big_array = np.random.randint(1,100, size =1000000)

In [23]:
big_array[:100]

array([87,  5, 91, 21, 54,  5, 24, 64, 85, 53, 19, 58, 92, 44, 40, 59, 98,
       27, 82, 39, 64, 54, 30, 86, 70, 86, 29, 94, 87,  7, 60,  7,  4, 29,
       80, 92, 63, 52, 99, 41,  7, 85,  2,  9, 98, 20, 60, 41,  2, 34, 87,
       41,  1, 54, 64, 66, 14, 87,  6, 29, 32, 30, 19, 29, 92, 80, 89, 23,
       39, 37, 78, 47, 21,  2, 58, 70, 23, 64, 65, 39, 41, 25, 28, 17, 32,
       21, 66, 84, 97, 53, 48, 92, 51, 36, 72, 50, 40, 51, 90, 16],
      dtype=int32)

In [19]:
%%timeit

# [+] Python loop를 통한 역수 계산 
compute_reciprocals(big_array)

3.42 s ± 292 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
%%timeit

# [+] NumPy ufunc을 통한 벡터화된 역수 계산
1 / big_array

3.79 ms ± 568 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### <strong>유니버설 함수들</strong>

In [38]:
# 난수 배열 2개 생성
np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)

print(arr1, arr2)

[5 8 9 5 0] [0 1 7 6 9]


In [39]:
# 배열-스칼라 연산
arr1 = arr1 - 2
print(arr1)

[ 3  6  7  3 -2]


In [40]:
# 배열-배열 연산
arr3 = arr1 + arr2
print(arr3)

[ 3  7 14  9  7]


In [42]:
# 다차원 배열 연산: 2차원 배열 ** 스칼라  차원이 다른 배열끼리 연산을 빠르게 가능케 함 - numpy
arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[[9 7 6 9 1]
 [0 1 8 8 3]
 [9 8 7 3 6]]
[[81 49 36 81  1]
 [ 0  1 64 64  9]
 [81 64 49  9 36]]


In [ ]:
"""
    UFuncs: 산술 연산
"""

# 기본 산술 연산
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** 2)

# 산술 연산에 대응하는 유니버설 함수
print("x + 5 =", np.add(x, 5))
print("x - 5 =", np.subtract(x, 5))
print("x * 2 =", np.multiply(x, 2))
print("x / 2 =", np.divide(x, 2))
print("x ** 2 =", np.power(x, 2))


In [43]:
"""
    UFuncs: 절댓값 계산
"""

# [+] 절댓값 함수
x = np.array([-2, -1, 0, 1, 2])
np.abs(x)

array([2, 1, 0, 1, 2])

In [44]:
"""
    np.linspace(start, stop, num): 선형 간격 벡터 생성
        - start: 벡터의 시작 값
        - end: 벡터의 종료 값
        - num: 생성할 값의 개수
"""

# [+][0, 100]의 범위를 가지며, 균일한 간격의 5개의 값들로 구성되는 벡터를 생성
x = np.linspace(0,100, 5)
x

array([  0.,  25.,  50.,  75., 100.])

In [46]:
# [+] [0, 100]의 범위를 가지며, [0, 10, 20, 30, ..., 100]와
# 같은 값들로 구성되는 벡터를 생성
x = np.linspace(0,100, 11)
x

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [47]:
# 삼각함수(trigonometric functions)
theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [48]:
"""
    집계 함수: reduce()
"""

# 배열 생성
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [50]:
# [+] 덧셈 연산으로 집계
aggr = np.add.reduce(x)
aggr

np.int64(10)

In [51]:
# [+] 곱셈 연산으로 집계
aggr = np.multiply.reduce(x)
aggr

np.int64(24)

In [53]:
"""
    집계 함수: accumulate()
"""

# [+] 덧셈 연산으로 집계
accum = np.add.accumulate(x)
accum

array([ 1,  3,  6, 10])

In [54]:
# [+] 곱셈 연산으로 집계
accum = np.multiply.accumulate(x)
accum

array([ 1,  2,  6, 24])

In [55]:
# 집계 함수: sum()
np.random.seed(3) #랜덤 시드 for 재현성
arr =  np.random.rand(1000000)# [+] 0~1 사이의 실수 형태의 난수 배열 생성

print(arr)
print("sum =", np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum = 500422.19897015323


In [56]:
# sum(): Python 내장함수
%timeit sum(arr)

112 ms ± 4.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [57]:
# np.sum()
%timeit np.sum(arr) # 1000µs = 1ms

1.24 ms ± 32.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [66]:
# [+] 그 외의 집계함수
print("max =", np.max(arr))
print("min =", np.min(arr))
print("mean =", np.mean(arr))
print("median =", np.median(arr))
print("percentile =", np.percentile(arr , 90))
print("variance =", np.var(arr))
print("standard deviation =", np.std(arr))
print("index of maximum value =", np.argmax(arr))
print("index of minimum value =", np.argmin(arr))
print("Is there any number greater than 1? =", np.any(arr > 1))
print("Is every number greater than 0? =", np.all(arr)) 

max = 0.9999996367889004
min = 1.5496004267534502e-06
mean = 0.5004221989701533
median = 0.5005659265960778
percentile = 0.9001765340710965
variance = 0.08331685347394584
standard deviation = 0.28864658922971154
index of maximum value = 339543
index of minimum value = 980213
Is there any number greater than 1? = False
Is every number greater than 0? = True


In [67]:
"""다차원 집계"""

# 2차원 난수 배열 생성
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
arr

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [68]:
# [+] 행 방향으로 집계 (row sum)
np.sum(arr, axis=0)

array([14, 13, 13, 14])

In [69]:
# [+] 열 방향으로 집계 (column sum)
np.sum(arr, axis=1)

array([11, 24, 19])